### ISSUE TITLE
Upgrade readdirp to 2.0.1 

### ISSUE THREAD

**Issue by edsadr** [barc/express-hbs#102]
Please update In order to avoid a RegExp DoS issue, nsp advisory 118

**Comment by BobDickinson** [comment]
Would also very much appreciate a near term release with new readdirp, which includes new minimatch (3.0.2).  Right now, installing express-hbs throws this warning:

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

That's pretty ugly for users of our products which include express-hbs.

**Comment by ErisDS** [comment]
Thanks for swinging by and letting me know this needed doing! I've merged @edsadr's PR and released this as 1.0.2.

Let me know if there are any issues.
