### ISSUE TITLE
is precompiling the templates supported ?

### ISSUE THREAD

**Issue by piyushbeli** [barc/express-hbs#104]
We are facing a serious rendering issue in our application, most of the time request is busy in rendering the page and CPU usages while that time is around 100%.
I tried to compare the library with EJS (by rendering the same page) and EJS was almost 4 times faster than handlebar and CPU usgaes were also not very high.
Is there any issue with the module or it is the known behavior of handlebar templates.

I though if we keeo the precompiled templates in express-hbs module then it might lower down the rendering time when lot of different partials creates a single page, do you have any in built support for this ?

Can we use https://www.npmjs.com/package/hbs-precompiler module for the purpose, if yes then what will be the configuration in express-hbs to fetch the template from template.js

Many thanks
Piyush

**Comment by ErisDS** [comment]
This question is pretty old now I realise, sorry! There is a response about precompiling here: https://github.com/barc/express-hbs/issues/5
