### ISSUE TITLE
Can express-hbs use paragraph functions like express-Handlebars?

### ISSUE THREAD

**Issue by caihuattkl** [barc/express-hbs#120]
Can express-hbs use paragraph functions like express-Handlebars?

app.engine('hbs', exphbs.express4({
	partialsDir: './views/template/partials/',
	layoutsDir: "./views/template/layouts/",
	defaultLayout:'./views/template/layouts/layout-default',
	extname: '.hbs',
	helpers: {
		section: function(name, options) {
			if(!this._sections) this._sections = {};
			this._sections[name] = options.fn(this);
			console.log(name,options)
			return null;
		}
	}

}));

Why did I have no effect after configuration?

**Comment by ErisDS** [comment]
I'm not sure what you mean by paragraph functions?

There is no `helpers` configuration option in express-hbs, you would need to use the registerHelper() function to register any helpers.

Hopefully this answers your question, if not please come back and provide more details :)

**Comment by caihuattkl** [comment]
Has been resolved, thank you very much!
Function similar to {{#contentFor "Keywords"}}{{keywords}}{{/contentFor}} so!
