### ISSUE TITLE
Can express-hbs dynamically return code fragments?

### ISSUE THREAD

**Issue by caihuattkl** [barc/express-hbs#121]
**The following code is wrong, but I just want to achieve dynamic return code fragment.Express-hbs can be achieved?**

exphbs.registerHelper('if_channelSlide', function(v1, opt) {
	if(v1=='jinrong'){
		return opt.fn('{{>channel-slide-jinrong}}');
	}else if(v1=='zhengquan'){
		return opt.fn('{{>channel-slide-stock}}');
	}else{
		return opt.fn('{{>channel-slide}}');
	}
});

**Comment by jtwebman** [comment]
@caihuattkl Did you find an way to do this?

**Comment by ErisDS** [comment]
Closing out all old issues. If this is still an issue with the latest version please let us know.
