### ISSUE TITLE
Partial with context not working

### ISSUE THREAD

**Issue by alexandrucancescu** [barc/express-hbs#139]
I am trying to use a partial with context as described in handlebars documentation.
I have:
`res.render("index",{title="helloworld"})`
Layout:
`{{>footer}}`
Partial footer:
`<script>alert({{title}}</script>`
In the example above it doesn't even show an alert. However if I call footer from Layout like this:
`{{>footer title}}`
It alerts with an empty dialog.
I also tried `{{>footer title=title}}` or `{{>footer title="other"}}`
Even tried to call footer partial with all of the above directly from index but the same effect.

<h4>Sorry my bad! Forgot quotation marks on <code>alert("{{title}}")</code> </h4>

**Comment by jtwebman** [comment]
Trying to catch this project up. Is this still an issue with master?

**Comment by ErisDS** [comment]
Closing out all old issues. If this is still an issue with the latest version please let us know.
