### ISSUE TITLE
Block content array must be concated with newline, not stringified

### ISSUE THREAD

**Issue by EriksRemess** [barc/express-hbs#153]
`block` stringifies array of all referenced to it `contentFor` contents. That adds a comma between them. By handlebar spec and by previous behaviour of this Node module, array of assigned block items should be concated with newlines.
I have created pull request that fixes this issue:
https://github.com/barc/express-hbs/pull/152

**Comment by jtwebman** [comment]
Thank you for the PR. Sorry this was missed, any chance you can also add a test for this so it isn't missed in the future?

**Comment by jtwebman** [comment]
#152 was merged and release in 2.0.1, closing the ticket.
