### ISSUE TITLE
per-request helper

### ISSUE THREAD

**Issue by iJosephY** [barc/express-hbs#159]
i"m having a problem where i have a name variable set in a helper
sometimes when others browse the page that i use the helper in ..
they see names of other visitors and it happened many times

i define the name in a middle-ware then pass it inside a helper like this

```
this.app.use(function(req, res, next){

hbs.registerHelper('UserName', function(){
return clientInfo.client_nickname;
}

});
```

so if visitor 1 enters the page while visitor 2 is browsing it aswell
it show visitor 2 name to visitor 1

hope you understand me and i hope you have a solution for me

**Comment by allouis** [comment]
@iJosephY You can set the `UserName` property on `res.locals` and then use it inside your template like this:

```js
this.app.use(function (req, res, next) {
	res.locals.UserName = clientInfo.client_nickname

    // later
    res.render('some-template');
});
```

And then in your template

```html
<h1> Hello, {{UserName}} </h1>
```

**Comment by iJosephY** [comment]
i didn't know that exists, thanks you ..
