### ISSUE TITLE
Change delimiters

### ISSUE THREAD

**Issue by mquintal** [barc/express-hbs#58]
Is there any way to change express-hbs delimiter?
What I pretend is change default delimiter {{ something }} to [[ something ]]. I need to create an app which needs to "pre-render" templates in server-sidle and then send these templates to AngularJS front-end application.
Thank you.

**Comment by springuper** [comment]
+1

**Comment by ErisDS** [comment]
This is (as you [have already discovered](https://github.com/wycats/handlebars.js/issues/350#issuecomment-224477191)) a restriction in the way handlebars works and not something that express-hbs can work around.

The handlebars issue you discovered explains that you may be able to build a custom version of handlebars to do this.
