### ISSUE TITLE
Using without express

### ISSUE THREAD

**Issue by fsbdev** [barc/express-hbs#70]
I would like to use your layouts logic but I'm not using Express, how can I simply mixin the layout functionality to my instance of handlebars?

**Comment by fsbdev** [comment]
Looking at the code it seems you didn't design it in a way that the layout functionality could be used on its own..

**Comment by CTAPbIuMABP** [comment]
```
var func = hbs.express3({
	partialsDir: "partials",
	layoutsDir: "layouts",
	extname: ".hbs"
})
func("template.hbs", source, [options,] callback);
```

**Comment by mgutz** [comment]
thanks @CTAPbIuMABP
