### ISSUE TITLE
Nested layouts support

### ISSUE THREAD

**Issue by omarfouad** [barc/express-hbs#74]
Is there a way to nest a layout inside of another? For example:

```
default.hsb
-- postLayoout.hbs
---- {{{body}}}

```

Thanks in advance.

**Comment by mgutz** [comment]
Is this what your looking for?

https://github.com/barc/express-hbs/blob/master/example/views/layout/veggie-details.hbs

```
html-struct.hbs
    veggies.hbs
        veggie-details.hbs
```

**Comment by omarfouad** [comment]
I'm not sure if that's going to behave as I need. For example, given the following in a router callback:

```js

router.get('/post/:id, function(req, res) {
   // gets article from db ...
   
   res.render('article', {
      post: article,
      layout('layouts/postLayout') // This would yield the article view in postLayoout
   }
})
```

Then in the `article.hsb` view:
   {{!< defaultLayout}}
   
   <p> and everything here will be inside of the defaultLayout specified above?</p>
```html



```

**Comment by mgutz** [comment]
In your example, defaultLayout will be used by order of precedence rules in the README, which would ignore `layout` in the context argument. The reasoning is if you put a declarative layout in a page, you probably meant to override the setting in code.

**Comment by omarfouad** [comment]
Ok, so I shouldn't specify the layout in the JS code. 
I suppose it works like this:

in `article.hbs`
```HTML
{{!< postLayout}}
<p> and everything here will be inside of the defaultLayout specified above?</p>
```

in `postLayout.hbs`
```HTML
<h1>This is a post</h1>
{{{body}}} 
```

in `defaultLayout.hbs`
```HTML
<html>
<head>...</head>
<body>
   {{{body}}} <- does this render postLayout with the article.hbs view in it?
</body>
</html>
```

Is this right?

**Comment by mgutz** [comment]
`postLayout.hbs` should look like this to tell hbs it is nested within defaultLayout

```
{{!< defaultLayout }}
<h1>This is a post</h1>
{{{body}}} 
```

**Comment by omarfouad** [comment]
Yes! That makes sense. 
Thanks!

**Comment by alexandrucancescu** [comment]
Guys sorry for contacting you this way but just wanted to say a huge thanks for this awesome implementation, is the most complete and elegant view engine for express. Keep up the good work!
