### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings thrown from cachePartials

### ISSUE THREAD

**Issue by ErisDS** [barc/express-hbs#76]
If you call `cachePartials` without `render` or some other way of causing the viewsDir to be set, the error 'Uncaught TypeError: Arguments to path.resolve must be strings' is thrown, as of express-hbs 0.8.2 (note I've only seen this error on node 0.10.37 & 0.12).

I am not sure if it is expected that calling `cachePartials` on it's own should work. In Ghost we were using `cachePartials` in order to make the partials available for some tests. It can be worked around by calling render on a random template instead.

It is worth noting anyone depending on this functionality would have experienced a breaking change between 0.8.1 and 0.8.2 which is probably undesirable, even if the code was never intended to be used this way.

The issue is a side effect of [this change made to resolve #73](https://github.com/barc/express-hbs/commit/147aac1efb245b55980d7559a723eb580fdd66c2#diff-0646323334941cee08c9e424acbee543R341):
 
![](http://puu.sh/gHcJd.png)

By passing `filename` through to `compile`, this block now gets executed: https://github.com/barc/express-hbs/blob/master/lib/hbs.js#L368

```
if (filename) {
    if (Array.isArray(this.viewsDir) && this.viewsDir.length > 0) {
      compiled.__filename = path.relative(this.cwd, filename).replace(path.sep, '/');
    } else {
      compiled.__filename = path.relative(this.viewsDir, filename).replace(path.sep, '/');
    }
  }
```

It checks if `this.viewsDir`is an array, and if not passes it to `path.relative`, which causes the error, as there is no check that `this.viewsDir` is not null/undefined.

The fix is very simple, PR incoming.

---

As an aside, the documentation states that `partialsDir` is the only required option to be passed to `express3` or `express4`. Most of the tests however are setting `viewsDir` and nothing more, and yet as far as I can tell that doesn't do anything until render is called? Just a bit confused about the expectations.

**Comment by mgutz** [comment]
Most of the tests are boilerplate copies so there are likely unnecessary options, but the asserts should be unique.

Setting ViewsDir to an empty string is the right approach. Thank you.
