### ISSUE TITLE
Views directory not set in Express4

### ISSUE THREAD

**Issue by whynotmatt** [barc/express-hbs#83]
I setup my app using the example in the documentation and set my views directory using:

```
app.set('views', relative('views'));
```

But then when I tried to view my webpage, I got an error from line 447 of the hbs.js file that the options.settings.view variable was undefined. When I debug stepped through the call, I noticed that the options.settings object was undefined. So that was the cause of the error.

I did find a simple work around, but it involved editing the hbs.js file and I would prefer to use released versions.

First, I had to set the viewsDir option while setting up hbs:

```
app.engine('hbs', hbs.express4({
    partialsDir:relative('views/partials'),
    defaultLayout:relative('views/layouts/main.hbs),
    layoutsDir: relative('views/layouts'),
    viewsDir: relative('views')
}));
```

Then I had to replace line 447 in hbs with this:

```
if (options.settings) {
    this.viewsDir = options.settings.views || this.viewsDirOpt;
  }
  else {
    this.viewsDir = this.viewsDirOpt;
  }
```

Now everything works. But I'm not sure why I was getting the error in the first place when I was following the example.

**Comment by oliverguj** [comment]
+1

I saw this, too, when using app.render instead of res.render.

workaraund: pass a property `"settings": {}` along with the locals, e.g.

```
app.render('template', {
   layout: 'layout.hbs',
   _locals: ampJson,
  settings: { }
  });

**Comment by Avcajaraville** [comment]
Ok, this is super old topic, but I think this is happening only if somehow you overwrite your app.locals... 

Im now checking:
- Correct way of using "global variables".
- Why doest express-hbs reads locals.

I have been experiencing this problem my self and Im pretty sure that could be the reason.

**Comment by jtwebman** [comment]
Is this still an issue?

**Comment by ErisDS** [comment]
Closing out all old issues. If this is still an issue with the latest version please let us know.
