### ISSUE TITLE
how can i override layoutPath() ?

### ISSUE THREAD

**Issue by dynnamitt** [barc/express-hbs#87]
I belive I cannot customize/override (in my client code) this func in hbs.js

```
ExpressHbs.prototype.layoutPath()
```

coffeescript sample not working for me;

```
exphbs = require 'express-hbs'
originalLayoutPath = exphbs.layoutPath
exphbs.layoutPath = (filename,layout) ->
  console.log "I never see this output"
  originalLayoutPath filename,layout

# express3 init below
```

What did I miss there??

**Comment by ErisDS** [comment]
I know this is super old, but `layoutsDir` is the name of the config option and it expects a string :)
