### ISSUE TITLE
Upgrade readdirp to 1.4.0 (Node 6.0 warning)

### ISSUE THREAD

**Issue by BobDickinson** [barc/express-hbs#94]
When running with express-hbs 1.0.0 and Node 6.0.0:

    npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

express-hbs currently uses readdirp ~1.3.0, which uses a pretty old graceful-fs (~2.0.0).  

readdirp 1.4.0 was released 9 months ago, and the only change was to upgrade its graceful-fs to ~4.1.2.

It seems like upgrading to readdirp 1.4.0 is pretty safe and it would be great if this could be addressed in a near-term 1.0.1 release.

**Comment by ktkaushik** [comment]
yeah, i have been seeing this too

**Comment by ErisDS** [comment]
@BobDickinson thank you for writing a thorough upgrade report, very useful. Would you like to submit a PR to resolve this?

**Comment by ErisDS** [comment]
This was closed by #95
